version: '2.4'
services:
  pet-clinic-api:
    image: spring-petclinic-openapi
    ports:
    - '8080:8080'
    mem_limit: 512m
  pet-clinic-client:
    build: client
    image: spring-petclinic-openapi-client
    ports:
    - '4444:80'
    mem_limit: 128m
